var gopherClient=new GopherServerClient;
function GopherServerClient(){this.browserVoiceSupport=!1;this.voiceChat=null;if(!window.WebSocket)return null;navigator.mediaDevices.getUserMedia&&(this.browserVoiceSupport=!0,this.voiceChat=new GopherVoiceChat);this.ip="";this.port=0;this.socketURL="";this.ssl=!1;this.socket=null;this.guest=this.rememberMe=this.loggedIn=this.connected=!1;this.roomName=this.userName="";this.status=0;this.friends={};this.userVars={};this.clientActionDefs={signup:"s",deleteAccount:"d",changePassword:"pc",changeAccountInfo:"ic",
login:"li",logout:"lo",joinRoom:"j",leaveRoom:"lr",createRoom:"r",deleteRoom:"rd",roomInvite:"i",revokeInvite:"ri",chatMessage:"c",privateMessage:"p",voiceStream:"v",changeStatus:"sc",customAction:"a",requestFriend:"f",acceptFriend:"fa",declineFriend:"fd",removeFriend:"fr",setUserVariable:"vs",setUserVariables:"vx"};this.messageTypes={CHAT:0,PRIVATE:1,SERVER:2};this.serverMessageTypes={GAME:0,NOTICE:1,IMPORTANT:2};this.serverMessageNames=["Game","Notice","Important"];this.userStatusDefs=["Available",
"In Game","Idle","Offline"];this.friendStatusDefs={requested:0,pending:1,accepted:2};this.events={signup:"onsignup",accountDelete:"onaccountdelete",passwordChange:"onpasswordchange",accountInfoChange:"onaccountinfochange",autologInit:"onautologinit",autologFailed:"onautologfailed",autologNoFile:"onautolognofile",login:"onlogin",logout:"onlogout",connected:"onconnect",disconnected:"ondisconnect",joined:"onjoinroom",left:"onleaveroom",userJoined:"onuserjoin",userLeft:"onuserleft",roomCreate:"oncreateroom",
roomDelete:"ondeleteroom",invited:"oninvite",inviteRevoked:"onrevokeinvite",inviteReceived:"oninvitereceived",chatMessage:"onchatmessage",privateMessage:"onprivatemessage",serverMessage:"onservermessage",data:"ondata",statusChanged:"onstatuschanged",customAction:"oncustomaction",friendRequested:"onfriendrequested",friendAccepted:"onfriendaccepted",friendDeclined:"onfrienddecline",friendRemoved:"onfriendremove",friendRequestReceived:"onfriendrequestreceived",friendRequestAccepted:"onfriendrequestaccepted",
friendStatusChanged:"onfriendstatuschanged"};this.onFriendStatusChangeListener=this.onFriendRequestAcceptedListener=this.onFriendRequestRecievedListener=this.onRemoveFriendListener=this.onDeclineFriendListener=this.onAcceptFriendListener=this.onRequestFriendListener=this.onCustomActionListener=this.onStatusChangeListener=this.onDataListener=this.onServerMsgListener=this.onPrivateMsgListener=this.onChatMsgListener=this.onRecieveInviteListener=this.onRevokeListener=this.onInviteListener=this.onDeleteRoomListener=
this.onCreateRoomListener=this.onUserLeaveListener=this.onUserJoinListener=this.onLeaveRoomListener=this.onJoinRoomListener=this.onDisconnectListener=this.onConnectListener=this.onLogoutListener=this.onLoginListener=this.onAutoLogNoFileListener=this.onAutoLogFailListener=this.onAutoLogInitListener=this.onAccountInfoChangeListener=this.onPasswordChangeListener=this.onAccountDeleteListener=this.onSignupListener=null;this.paramError="An incorrect parameter type was supplied";return!0}
GopherServerClient.prototype.connect=function(a,b,c){if(a.constructor!=String||b.constructor!=Number||c.constructor!=Boolean)return this.paramError;this.ip=a;this.port=b;this.ssl=c;this.socketURL=1==c?"wss://"+a+":"+b+"/wss":"ws://"+a+":"+b+"/ws";this.socket=new WebSocket(this.socketURL);this.socket.addEventListener("open",this.sO);this.socket.addEventListener("close",this.sD);this.socket.addEventListener("message",this.sR)};GopherServerClient.prototype.disconnect=function(){this.socket.close()};
GopherServerClient.prototype.sO=function(a){a=gopherClient;a.connected=!0;if(null!=a.onConnectListener)a.onConnectListener()};GopherServerClient.prototype.sD=function(a){a=gopherClient;a.socket.removeEventListener("open",a.sO);a.socket.removeEventListener("close",a.sD);a.socket.removeEventListener("message",a.sR);a.connected=!1;a.loggedIn=!1;a.rememberMe=!1;a.guest=!1;a.userName="";a.roomName="";a.status=0;a.friends={};if(null!=a.onDisconnectListener)a.onDisconnectListener()};
GopherServerClient.prototype.sR=function(a){a=JSON.parse(a.data);gopherClient.sRhandle(a)};
GopherServerClient.prototype.addEventListener=function(a,b){if(null==a.constructor||a.constructor!=String||null==b||void 0===b||b.constructor!=Function)return this.paramError;a==this.events.signup?this.onSignupListener=b:a==this.events.passwordChange?this.onPasswordChangeListener=b:a==this.events.accountInfoChange?this.onAccountInfoChangeListener=b:a==this.events.accountDelete?this.onAccountDeleteListener=b:a==this.events.login?this.onLoginListener=b:a==this.events.logout?this.onLogoutListener=b:
a==this.events.connected?this.onConnectListener=b:a==this.events.disconnected?this.onDisconnectListener=b:a==this.events.joined?this.onJoinRoomListener=b:a==this.events.left?this.onLeaveRoomListener=b:a==this.events.userJoined?this.onUserJoinListener=b:a==this.events.userLeft?this.onUserLeaveListener=b:a==this.events.roomCreate?this.onCreateRoomListener=b:a==this.events.roomDelete?this.onDeleteRoomListener=b:a==this.events.invited?this.onInviteListener=b:a==this.events.inviteRevoked?this.onRevokeListener=
b:a==this.events.inviteRecieved?this.onRecieveInviteListener=b:a==this.events.chatMessage?this.onChatMsgListener=b:a==this.events.privateMessage?this.onPrivateMsgListener=b:a==this.events.serverMessage?this.onServerMsgListener=b:a==this.events.data?this.onDataListener=b:a==this.events.statusChanged?this.onStatusChangeListener=b:a==this.events.customAction?this.onCustomActionListener=b:a==this.events.friendRequested?this.onRequestFriendListener=b:a==this.events.friendAccepted?this.onAcceptFriendListener=
b:a==this.events.friendDeclined?this.onDeclineFriendListener=b:a==this.events.friendRemoved?this.onRemoveFriendListener=b:a==this.events.friendRequestRecieved?this.onFriendRequestRecievedListener=b:a==this.events.friendRequestAccepted?this.onFriendRequestAcceptedListener=b:a==this.events.friendStatusChanged?this.onFriendStatusChangeListener=b:a==this.events.autologInit?this.onAutoLogInitListener=b:a==this.events.autologFailed?this.onAutoLogFailListener=b:a==this.events.autologNoFile&&(this.onAutoLogNoFileListener=
b)};
GopherServerClient.prototype.removeEventListener=function(a){if(a.constructor!=String)return this.paramError;a==this.events.signup?this.onSignupListener=null:a==this.events.passwordChange?this.onPasswordChangeListener=null:a==this.events.accountInfoChange?this.onAccountInfoChangeListener=null:a==this.events.accountDelete?this.onAccountDeleteListener=null:a==this.events.login?this.onLoginListener=null:a==this.events.logout?this.onLogoutListener=null:a==this.events.connected?this.onConnectListener=null:
a==this.events.disconnected?this.onDisconnectListener=null:a==this.events.joined?this.onJoinRoomListener=null:a==this.events.left?this.onLeaveRoomListener=null:a==this.events.userJoined?this.onUserJoinListener=null:a==this.events.userLeft?this.onUserLeaveListener=null:a==this.events.roomCreate?this.onCreateRoomListener=null:a==this.events.roomDelete?this.onDeleteRoomListener=null:a==this.events.invited?this.onInviteListener=null:a==this.events.inviteRevoked?this.onRevokeListener=null:a==this.events.inviteRecieved?
this.onRecieveInviteListener=null:a==this.events.chatMessage?this.onChatMsgListener=null:a==this.events.privateMessage?this.onPrivateMsgListener=null:a==this.events.serverMessage?this.onServerMsgListener=null:a==this.events.data?this.onDataListener=null:a==this.events.statusChanged?this.onStatusChangeListener=null:a==this.events.customAction?this.onCustomActionListener=null:a==this.events.friendRequested?this.onRequestFriendListener=null:a==this.events.friendAccepted?this.onAcceptFriendListener=null:
a==this.events.friendDeclined?this.onDeclineFriendListener=null:a==this.events.friendRemoved?this.onRemoveFriendListener=null:a==this.events.friendRequestRecieved?this.onFriendRequestRecievedListener=null:a==this.events.friendRequestAccepted?this.onFriendRequestAcceptedListener=null:a==this.events.friendStatusChanged?this.onFriendStatusChangeListener=null:a==this.events.autologInit?this.onAutoLogInitListener=null:a==this.events.autologFailed?this.onAutoLogFailListener=null:a==this.events.autologNoFile&&
(this.onAutoLogNoFileListener=null)};
GopherServerClient.prototype.sRhandle=function(a){void 0!==a.v&&this.voiceChat.rD(a.v);if(void 0!==a.vp)this.voiceChat.pD();else if(void 0!==a.d){if(null!=this.onDataListener)this.onDataListener(a.d)}else if(void 0!==a.a)this.customClientActionResponse(a.a);else if(void 0!==a.c)a.c.a==this.clientActionDefs.setUserVariable?this.setUserVariableReceived(a.c):a.c.a==this.clientActionDefs.setUserVariables?this.setUserVariablesReceived(a.c):a.c.a==this.clientActionDefs.signup?this.signupResponse(a.c):a.c.a==
this.clientActionDefs.deleteAccount?this.deleteAccountResponse(a.c):a.c.a==this.clientActionDefs.changeAccountInfo?this.changeAccountInfoResponse(a.c):a.c.a==this.clientActionDefs.changePassword?this.changePasswordResponse(a.c):a.c.a==this.clientActionDefs.login?this.loginReponse(a.c):a.c.a==this.clientActionDefs.logout?this.logoutReponse(a.c):a.c.a==this.clientActionDefs.joinRoom?this.joinRoomResponse(a.c):a.c.a==this.clientActionDefs.leaveRoom?this.leaveRoomResponse(a.c):a.c.a==this.clientActionDefs.createRoom?
this.createRoomResponse(a.c):a.c.a==this.clientActionDefs.roomInvite?this.sendInviteResponse(a.c):a.c.a==this.clientActionDefs.revokeInvite?this.revokeInviteResponse(a.c):a.c.a==this.clientActionDefs.deleteRoom?this.deleteRoomResponse(a.c):a.c.a==this.clientActionDefs.requestFriend?this.requestFriendRecieved(a.c):a.c.a==this.clientActionDefs.acceptFriend?this.acceptFriendRecieved(a.c):a.c.a==this.clientActionDefs.declineFriend?this.declineFriendRecieved(a.c):a.c.a==this.clientActionDefs.removeFriend?
this.removeFriendRecieved(a.c):a.c.a==this.clientActionDefs.changeStatus&&this.changeStatusRecieved(a.c);else if(void 0!==a.e){if(null!=this.onUserJoinListener)this.onUserJoinListener(a.e.u,a.e.g)}else if(void 0!==a.x){if(null!=this.onUserLeaveListener)this.onUserLeaveListener(a.x.u)}else if(void 0!==a.m)if(void 0!==a.m.s){if(null!=this.onServerMsgListener)this.onServerMsgListener(a.m.s,a.m.m)}else{if(null!=this.onChatMsgListener)this.onChatMsgListener(a.m.a,a.m.m)}else if(void 0!==a.p){if(null!=
this.onPrivateMsgListener)this.onPrivateMsgListener(a.p.f,a.p.t,a.p.m)}else if(void 0!==a.i){if(null!=this.onRecieveInviteListener)this.onRecieveInviteListener(a.i.u,a.i.r)}else if(void 0!==a.f){if(this.friends[a.f.n]={name:a.f.n,requestStatus:this.friendStatusDefs.requested,status:-1},null!=this.onFriendRequestRecievedListener)this.onFriendRequestRecievedListener(a.f.n)}else if(void 0!==a.fa){if(void 0!=this.friends[a.fa.n]?(this.friends[a.fa.n].requestStatus=this.friendStatusDefs.accepted,this.friends[a.fa.n].status=
a.fa.s):this.friends[a.fa.n]={name:a.fa.n,requestStatus:this.friendStatusDefs.accepted,status:a.fa.s},null!=this.onFriendRequestAcceptedListener)this.onFriendRequestAcceptedListener(a.fa.n)}else if(void 0!==a.fr){if(void 0!=this.friends[a.fr.n]&&delete this.friends[a.fr.n],null!=this.onRemoveFriendListener)this.onRemoveFriendListener(a.fr.n)}else if(void 0!==a.fs){if(void 0!=this.friends[a.fs.n]?this.friends[a.fs.n].status=a.fs.s:this.friends[a.fs.n]={name:a.fs.n,requestStatus:this.friendStatusDefs.accepted,
status:a.fs.s},null!=this.onFriendStatusChangeListener)this.onFriendStatusChangeListener(a.fs.n,a.fs.s)}else if(void 0!==a.t){if(null!=this.onAutoLogInitListener)this.onAutoLogInitListener();localStorage.getItem("dt")?localStorage.getItem("da")&&localStorage.getItem("di")?this.socket.send(JSON.stringify({A:"2",P:{dt:localStorage.getItem("dt"),da:localStorage.getItem("da"),di:localStorage.getItem("di")}})):this.socket.send(JSON.stringify({A:"1",P:localStorage.getItem("dt")})):this.socket.send(JSON.stringify({A:"0",
P:null}))}else if(void 0!==a.ts)localStorage.setItem("dt",a.ts),this.socket.send(JSON.stringify({A:"1",P:localStorage.getItem("dt")}));else if(void 0!==a.ap)this.socket.send(JSON.stringify({A:"3",P:null})),localStorage.setItem("da",a.ap);else if(void 0!==a.af){if(localStorage.clear(),localStorage.setItem("dt",a.af.dt),null!=this.onAutoLogFailListener)this.onAutoLogFailListener(a.af.e)}else if(void 0!==a.ai&&null!=this.onAutoLogNoFileListener)this.onAutoLogNoFileListener()};
GopherServerClient.prototype.signup=function(a,b,c){if(null==a||null==b||a.constructor!=String||b.constructor!=String||null!=c&&c.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.signup,P:{n:a,p:b,c:c}}))};GopherServerClient.prototype.signupResponse=function(a){if(void 0!==a.e){if(null!=this.onSignupListener)this.onSignupListener(!1,a.e)}else if(null!=this.onSignupListener)this.onSignupListener(!0,null)};
GopherServerClient.prototype.deleteAccount=function(a,b,c){if(null==a||null==b||a.constructor!=String||b.constructor!=String||null!=c&&c.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.deleteAccount,P:{n:a,p:b,c:c}}))};
GopherServerClient.prototype.deleteAccountResponse=function(a){if(void 0!==a.e){if(null!=this.onAccountDeleteListener)this.onAccountDeleteListener(!1,a.e)}else if(null!=this.onAccountDeleteListener)this.onAccountDeleteListener(!0,null)};
GopherServerClient.prototype.changeAccountInfo=function(a,b){if(!this.loggedIn)return"You must be logged in to change your account info";if(null==a||a.constructor!=String||null==b||b.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.changeAccountInfo,P:{p:a,c:b}}))};
GopherServerClient.prototype.changeAccountInfoResponse=function(a){if(void 0!==a.e){if(null!=this.onAccountInfoChangeListener)this.onAccountInfoChangeListener(!1,a.e)}else if(null!=this.onAccountInfoChangeListener)this.onAccountInfoChangeListener(!0,null)};
GopherServerClient.prototype.changePassword=function(a,b,c){if(!this.loggedIn)return"You must be logged in to change your password";if(null==a||null==b||a.constructor!=String||b.constructor!=String||null!=c&&c.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.changePassword,P:{p:a,n:b,c:c}}))};
GopherServerClient.prototype.changePasswordResponse=function(a){if(void 0!==a.e){if(null!=this.onPasswordChangeListener)this.onPasswordChangeListener(!1,a.e)}else if(null!=this.onPasswordChangeListener)this.onPasswordChangeListener(!0,null)};
GopherServerClient.prototype.login=function(a,b,c,d,e){if(null==a||a.constructor!=String||null!=d&&d.constructor!=Boolean||null!=c&&c.constructor!=Boolean||null!=b&&b.constructor!=String||null!=e&&e.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.login,P:{n:a,p:b,g:d,r:c,c:e}}));this.guest=d;this.rememberMe=null==c?!1:c};
GopherServerClient.prototype.loginReponse=function(a){if(void 0!==a.e){if(this.guest=!1,null!=this.onLoginListener)this.onLoginListener("",a.e)}else{this.userName=a.r.n;this.loggedIn=!0;var b=a.r.f;if(void 0!=b&&null!=b)for(var c=0;c<b.length;c++){var d=-1;void 0!=b[c].s&&(d=b[c].s);this.friends[b[c].n]={name:b[c].n,requestStatus:b[c].rs,status:d}}a.r.ap&&this.rememberMe&&(localStorage.setItem("da",a.r.ap),localStorage.setItem("di",a.r.ai));if(null!=this.onLoginListener)this.onLoginListener(this.userName,
null)}};GopherServerClient.prototype.logout=function(){this.socket.send(JSON.stringify({A:this.clientActionDefs.logout}))};GopherServerClient.prototype.logoutReponse=function(a){if(void 0!==a.e){if(null!=this.onLogoutListener)this.onLogoutListener(!1,a.e)}else if(this.userName="",this.guest=this.loggedIn=!1,this.roomName="",this.status=0,this.friends={},localStorage.getItem("da")&&(localStorage.removeItem("da"),localStorage.removeItem("di")),null!=this.onLogoutListener)this.onLogoutListener(!0,null)};
GopherServerClient.prototype.joinRoom=function(a){if(null==a||a.constructor!=String)return this.paramError;this.roomName=a;this.socket.send(JSON.stringify({A:this.clientActionDefs.joinRoom,P:a}))};GopherServerClient.prototype.joinRoomResponse=function(a){if(void 0!==a.e){if(this.roomName="",null!=this.onJoinRoomListener)this.onJoinRoomListener("",a.e)}else if(null!=this.onJoinRoomListener&&null!=this.onJoinRoomListener)this.onJoinRoomListener(a.r,null)};GopherServerClient.prototype.leaveRoom=function(){this.socket.send(JSON.stringify({A:this.clientActionDefs.leaveRoom}))};
GopherServerClient.prototype.leaveRoomResponse=function(a){if(void 0!==a.e){if(null!=this.onLeaveRoomListener)this.onLeaveRoomListener(!1,a.e)}else if(a=this.roomName,this.roomName="",null!=this.onLeaveRoomListener)this.onLeaveRoomListener(a,null)};
GopherServerClient.prototype.createRoom=function(a,b,c,d){if(null==a||null==b||null==c||null==d||a.constructor!=String||b.constructor!=String||c.constructor!=Boolean||d.constructor!=Number)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.createRoom,P:{n:a,t:b,p:c,m:Math.round(d)}}))};
GopherServerClient.prototype.createRoomResponse=function(a){if(void 0!==a.e){if(null!=this.onCreateRoomListener)this.onCreateRoomListener("",a.e)}else if(this.roomName=a.r,null!=this.onCreateRoomListener)this.onCreateRoomListener(a.r,null)};GopherServerClient.prototype.deleteRoom=function(a){if(null==a||a.constructor!=String)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.deleteRoom,P:a}))};
GopherServerClient.prototype.deleteRoomResponse=function(a){if(void 0!==a.e){if(null!=this.onDeleteRoomListener)this.onDeleteRoomListener(!1,a.e)}else if(null!=this.onDeleteRoomListener)this.onDeleteRoomListener(!0,null)};GopherServerClient.prototype.sendInvite=function(a){if(null==a||a.constructor!=String)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.roomInvite,P:a}))};
GopherServerClient.prototype.sendInviteResponse=function(a){if(void 0!==a.e){if(null!=this.onInviteListener)this.onInviteListener(!1,a.e)}else if(null!=this.onInviteListener)this.onInviteListener(!0,null)};GopherServerClient.prototype.revokeInvite=function(a){if(null==a||a.constructor!=String)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.revokeInvite,P:a}))};
GopherServerClient.prototype.revokeInviteResponse=function(a){if(void 0!==a.e){if(null!=this.onRevokeListener)this.onRevokeListener(!1,a.e)}else if(null!=this.onRevokeListener)this.onRevokeListener(!0,null)};GopherServerClient.prototype.chatMessage=function(a){if(null==a||a.constructor!=String&&a.constructor!=Object&&a.constructor!=Array)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.chatMessage,P:a}))};
GopherServerClient.prototype.privateMessage=function(a,b){if(null==b||null==a||a.constructor!=String||b.constructor!=String&&b.constructor!=Object&&b.constructor!=Array)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.privateMessage,P:{u:a,m:b}}))};
GopherServerClient.prototype.customClientAction=function(a,b){if(a.constructor!=String||null!=b.constructor&&b.constructor!=Boolean&&b.constructor!=Number&&b.constructor!=String&&b.constructor!=Array&&b.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.customAction,P:{a:a,d:b}}))};
GopherServerClient.prototype.customClientActionResponse=function(a){if(void 0!==a.e){if(null!=this.onCustomActionListener)this.onCustomActionListener(null,null,a.e)}else if(null!=this.onCustomActionListener)this.onCustomActionListener(a.r,a.a,null)};
GopherServerClient.prototype.requestFriend=function(a){if(null==a||a.constructor!=String)return this.paramError;if(void 0!=this.friends[a])return"You cannot request '"+a+"' as a friend at this time";this.socket.send(JSON.stringify({A:this.clientActionDefs.requestFriend,P:a}))};
GopherServerClient.prototype.requestFriendRecieved=function(a){if(void 0!==a.e){if(null!=this.onRequestFriendListener)this.onRequestFriendListener(null,a.e)}else if(this.friends[a.r]={name:a.r,requestStatus:this.friendStatusDefs.pending,status:-1},null!=this.onRequestFriendListener)this.onRequestFriendListener(a.r,null)};
GopherServerClient.prototype.acceptFriend=function(a){if(null==a||a.constructor!=String)return this.paramError;if(void 0==this.friends[a])return"No friend by the name '"+a+"'";if(this.friends[a].requestStatus!=this.friendStatusDefs.requested)return"Cannot accept '"+a+"' as a friend";this.socket.send(JSON.stringify({A:this.clientActionDefs.acceptFriend,P:a}))};
GopherServerClient.prototype.acceptFriendRecieved=function(a){if(void 0!==a.e){if(null!=this.onAcceptFriendListener)this.onAcceptFriendListener(null,a.e)}else if(void 0!=this.friends[a.r.n]?(this.friends[a.r.n].requestStatus=this.friendStatusDefs.accepted,this.friends[a.r.n].status=a.r.s):this.friends[a.r.n]={name:a.r.n,requestStatus:this.friendStatusDefs.accepted,status:a.r.s},null!=this.onAcceptFriendListener)this.onAcceptFriendListener(a.r.n,null)};
GopherServerClient.prototype.declineFriend=function(a){if(null==a||a.constructor!=String)return this.paramError;if(void 0==this.friends[a])return"No friend by the name '"+a+"'";if(this.friends[a].requestStatus!=this.friendStatusDefs.requested)return"Cannot decline '"+a+"' as a friend";this.socket.send(JSON.stringify({A:this.clientActionDefs.declineFriend,P:a}))};
GopherServerClient.prototype.declineFriendRecieved=function(a){if(void 0!==a.e){if(null!=this.onDeclineFriendListener)this.onDeclineFriendListener(null,a.e)}else if(void 0!=this.friends[a.r]&&delete this.friends[a.r],null!=this.onDeclineFriendListener)this.onDeclineFriendListener(a.r,null)};
GopherServerClient.prototype.removeFriend=function(a){if(null==a||a.constructor!=String)return this.paramError;if(void 0==this.friends[a])return"No friend by the name '"+a+"'";this.socket.send(JSON.stringify({A:this.clientActionDefs.removeFriend,P:a}))};
GopherServerClient.prototype.removeFriendRecieved=function(a){if(void 0!==a.e){if(null!=this.onRemoveFriendListener)this.onRemoveFriendListener(null,a.e)}else if(void 0!=this.friends[a.r]&&delete this.friends[a.r],null!=this.onRemoveFriendListener)this.onRemoveFriendListener(a.r,null)};GopherServerClient.prototype.changeStatus=function(a){if(null==a||a.constructor!=Number||0>a)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.changeStatus,P:Math.round(a)}))};
GopherServerClient.prototype.changeStatusRecieved=function(a){if(void 0!==a.e){if(null!=this.onStatusChangeListener)this.onStatusChangeListener(null,a.e)}else if(this.status=a.r,null!=this.onStatusChangeListener)this.onStatusChangeListener(a.r,null)};GopherServerClient.prototype.setUserVariable=function(a,b){if(void 0==a||a.constructor!=String)return this.paramError;console.log(a+", "+b);this.socket.send(JSON.stringify({A:this.clientActionDefs.setUserVariable,P:{k:a,v:b}}))};
GopherServerClient.prototype.setUserVariableReceived=function(a){this.userVars[a.r.k]=a.r.v};GopherServerClient.prototype.setUserVariables=function(a){if(null==a||a.constructor!=Object)return this.paramError;this.socket.send(JSON.stringify({A:this.clientActionDefs.setUserVariables,P:a}))};GopherServerClient.prototype.setUserVariablesReceived=function(a){for(var b=Object.keys(a.r),c=0;c<b.length;c++)this.userVars[b[c]]=a.r[b[c]]};GopherServerClient.prototype.getUserVariable=function(a){return this.userVars[a]};
GopherServerClient.prototype.isConnected=function(){return this.connected};GopherServerClient.prototype.isLoggedIn=function(){return this.loggedIn};GopherServerClient.prototype.isGuest=function(){return this.guest};GopherServerClient.prototype.getUserName=function(){return this.userName};GopherServerClient.prototype.getRoom=function(){return this.roomName};GopherServerClient.prototype.getFriends=function(){return this.friends};GopherServerClient.prototype.getStatus=function(){return this.status};
GopherServerClient.prototype.statusName=function(a){if(!(void 0==a||null==a||a.constructor!=Number||0>a||a>this.userStatusDefs.length-1))return this.userStatusDefs[a]};GopherServerClient.prototype.voiceSupport=function(){return this.browserVoiceSupport};
