function GopherVoiceChat(){this.volume=1;this.vcPing=this.bSize=300;this.pT=0;this.oG=this.acO=null;this.mRa=[null,null];this.mRs=0;this.mS=null;this.mO=!1;this.vidEl=null;this.mList={};this.BUFFER_SIZE_SMALL=150;this.BUFFER_SIZE_MEDIUM=225;this.BUFFER_SIZE_LARGE=300}GopherVoiceChat.prototype.setVolume=function(a){void 0!==a&&null!=a&&a.constructor==Number&&(this.volume=1<a?1:0>a?0:a)};
GopherVoiceChat.prototype.setBufferSize=function(a){void 0!==a&&null!=a&&a.constructor==Number&&(this.bSize=Math.round(a),this.vcPing=Math.round(a/3))};GopherVoiceChat.prototype.startVoiceChannels=function(){this.acO=new AudioContext;this.vidEl=document.createElement("video")};GopherVoiceChat.prototype.muteUser=function(a){this.mList[a]=1};
GopherVoiceChat.prototype.openMic=function(){if(null==this.acO)return"[gopherChat.voiceChat] You must call gopherClient.voiceChat.startOutputChannel() to enable voice chat";if(!gopherClient.connected||!gopherClient.loggedIn||""==gopherClient.roomName)return"[gopherChat.voiceChat] You must be logged in and in a room to open the microphone";var a=this,c=navigator.mediaDevices.getUserMedia({audio:!0});c.then(function(b){a.mS=b;a.cMS(b)});c["catch"](function(a){console.log("[gopherChat.voiceChat]  Error reading input from microphone")});
this.mO=!0;return null};GopherVoiceChat.prototype.closeMic=function(){if(null==this.acO)return"[gopherChat.voiceChat] You must call gopherClient.voiceChat.startOutputChannel() to enable voice chat";null!=this.mS&&this.mS.getAudioTracks()[0].stop();null!=this.mRa[0]&&(this.mRa[0].stop(),this.mRa[0]=null);null!=this.mRa[1]&&(this.mRa[1].stop(),this.mRa[1]=null);this.mRa=[null,null];this.mRs=0;this.mO=!1;return null};
GopherVoiceChat.prototype.cMS=function(a){var c=this;this.mS=a;this.mRa[this.mRs]=new MediaRecorder(a,{mimeType:"audio/webm;codecs=opus"});this.mRa[this.mRs].start();this.mRa[this.mRs].ondataavailable=function(a){if(!(50>=a.data.size)){c.pT=performance.now();var b=new FileReader;b.onloadend=function(){gopherClient.socket.send(JSON.stringify({A:gopherClient.clientActionDefs.voiceStream,P:b.result}))};b.readAsDataURL(a.data)}};setTimeout(this.cMSr,this.bSize)};
GopherVoiceChat.prototype.cMSr=function(){var a=gopherClient.voiceChat;null!=a.mRa[a.mRs]&&a.mS.active&&(a.mRs=1==a.mRs?0:1,a.mO&&a.cMS(a.mS),setTimeout(a.cMSrob,a.vcPing))};GopherVoiceChat.prototype.cMSrob=function(){var a=gopherClient.voiceChat;1==a.mRs?null!=a.mRa[0]&&a.mS.active&&(a.mRa[0].stop(),a.mRa[0]=null):null!=a.mRa[1]&&a.mS.active&&(a.mRa[1].stop(),a.mRa[1]=null)};
GopherVoiceChat.prototype.rD=function(a){var c=gopherClient.voiceChat;userName=a.u;void 0==this.mList[userName]&&(blobFromText=new Blob([convertDataURIToBinary(a.d)],{type:"audio/webm;codecs=opus"}),50>=blobFromText.size||this.getBlobDuration(blobFromText).then(function(a){var b=new FileReader;b.onloadend=function(){c.acO.decodeAudioData(b.result).then(function(b){var d=c.acO.createBufferSource();d.buffer=b;b=c.acO.createGain();b.gain.value=c.volume;d.connect(b);b.connect(c.acO.destination);b.gain.setValueAtTime(.01,
0);b.gain.exponentialRampToValueAtTime(c.volume,.005);b.gain.setValueAtTime(c.volume,a-.005);b.gain.exponentialRampToValueAtTime(.01,a);d.start()})["catch"](function(a){console.log(a)})};b.readAsArrayBuffer(blobFromText)}))};GopherVoiceChat.prototype.pD=function(){var a=100*(performance.now()-this.pT);this.vcPing=(this.vcPing+a)/2};var BASE64_MARKER=";base64,";
function convertDataURIToBinary(a){var c=a.indexOf(BASE64_MARKER)+BASE64_MARKER.length;a=a.substring(c);a=window.atob(a);c=a.length;var b=new Uint8Array(new ArrayBuffer(c));for(i=0;i<c;i++)b[i]=a.charCodeAt(i);return b}
GopherVoiceChat.prototype.getBlobDuration=function(a){var c=this,b=this,e=new Promise(function(a){return c.vidEl.addEventListener("loadedmetadata",function(){Infinity===b.vidEl.duration?(b.vidEl.currentTime=Number.MAX_SAFE_INTEGER,b.vidEl.ontimeupdate=function(){b.vidEl.ontimeupdate=null;a(b.vidEl.duration);b.vidEl.currentTime=0}):a(b.vidEl.duration)})});this.vidEl.src=window.URL.createObjectURL(a);return e};
